name: Hello

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: add comment to opened PR
        run: |
          COMMENT=$(cat .github/workflows/conf/comments.md)
          gh pr comment ${{ github.event.number }} -b "$COMMENT"

  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: get diff
        run: git fetch origin ${{ github.base_ref }} --depth=1
      - id: diff
        run: echo "::set-output name=changed::$(git diff --name-only origin/${{ github.base_ref }} HEAD --relative ./フォルダ名/ | wc -l)"
#      - if: ${{ steps.diff.outputs.changed != '0' }}
#        run: echo
