name: Hello

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: working check
        run: echo "workflow runs"
      - name: add comment to opened PR
        run: |
          COMMENT=$(cat .github/workflows/conf/comments.md)
          gh pr comment ${{ github.event.number }} -b "$COMMENT"
