name: Hello

on:
  workflow_call:
    inputs:
      enable_pr_comment:
        description: 'Enable PR comment'
        required: false
        default: true
        type: 'boolean'

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: working check
        run: echo "workflow runs"
      - name: create comment file
        run: |
          cat  << EOF > comment.md
          ## This is comment
          - [ ] check list
          EOF
      - name: add comment to opened PR
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
